### 4.1 NumPy ndarray : 다차원 배열 객체

#### ndarray란?
1. N차원의 배열 객체
2. 대규모의 데이터를 담을 수 있으며 빠르고 유연한 자료구조
3. 같은 종류의 데이터를 담는 포괄적 다차원 배열
- 모든 원소는 같은 자료형이어야함

#### shape?
1. 각 차원의 크기를 알려주는 튜플

#### dtype?
1. 배열에 저장된 자료형을 알려줌

In [86]:
import numpy as np

#ndarry
data = np.random.randn(2, 3) #(2, 3)배열을 갖는 랜덤한 ndarray 생성
data

array([[ 0.39021721, -0.23003977,  0.31474967],
       [ 0.52045811,  0.14171244,  0.6672722 ]])

In [87]:
#곱셈 연산

In [88]:
#덧셈 연산
data + data

array([[ 0.78043441, -0.46007954,  0.62949934],
       [ 1.04091621,  0.28342487,  1.33454439]])

In [89]:
#shape
data.shape

(2, 3)

In [90]:
#dtype
data.dtype

dtype('float64')

#### 4.1.1 ndarray 생성
1. array : 입력 데이터를 ndarray로 변환
    - 같은 길이를 가지고 있는 리스트인 경우 다차원 배열로 변환
2. np.zeros / np.ones : 주어진 길이 혹은 모양에 각각 0, 1로 채워진 배열을 생성
3. np.arange : 0부터 입력받은 수만큼 생성

In [91]:
data1 = [[1, 2, 3, 4, 5, 6, 2.5],[2, 5, 6, 2.3, 4.2, 2, 3],[1, 1, 1, 1, 1, 1, 1,]]

arr1 = np.array(data1)
arr1

array([[1. , 2. , 3. , 4. , 5. , 6. , 2.5],
       [2. , 5. , 6. , 2.3, 4.2, 2. , 3. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. ]])

In [92]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [93]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
np.zeros((3, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [95]:
np.empty((2,2))

array([[2.31584178e+077, 2.31584178e+077],
       [3.11108181e+231, 2.82466534e-309]])

#### 4.1.2 ndarray의 dtype

1. dtype
    - dtype은 데이터, 메타데이터를 담고 있는 객체
    - 자료형을 지정해줄 수 있음

2. astype
    - dtype을 입력받은 자료형으로 변환

In [103]:
arr2 = np.array([1, 2, 3], dtype=np.float64)
arr2.dtype

dtype('float64')

In [104]:
arr3 = np.array([1, 2, 3], dtype=np.int32)
arr3

array([1, 2, 3], dtype=int32)

In [105]:
arr4 = np.array([1, 2, 3], dtype=np.complex128)
arr4

array([1.+0.j, 2.+0.j, 3.+0.j])

In [106]:
int_arr2 = arr2.astype('int32')
int_arr2

array([1, 2, 3], dtype=int32)

In [107]:
float_arr3 = arr3.astype('float64')
float_arr3.dtype

dtype('float64')

In [108]:
#숫자형식 문자열을 숫자로 변환 가능
numeric_strings = np.array(['1.25', '4.22', '6.33'], dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [109]:
float_numeric_strings = numeric_strings.astype('float64')
float_numeric_strings.dtype

dtype('float64')